---
title: "MoreFigures"
format: html
editor: visual
---

```{r Setup, warning=FALSE, message=FALSE}
library(tidyverse)
library(patchwork)
library(ggsignif)
library(kableExtra)
library(ggrepel)
data <- read.csv("data_all.csv", skip = 1)
```

## Supported Graph

```{r}
df_supported <- data %>% 
  rename(Supported = Did.you.feel.supported.from.your.institution..department..team..etc...,
         Changed = How.has.COVID.19.changed.and.or.altered.your.academic.or.professional.plans...Some.examples..programs.you.will.apply.to..jobs.you.will.apply.to..interest.level.in.certain.career.paths.) %>% 
  select(Supported, Changed)

df_supported <- df_supported %>%
  mutate(Supported = case_when(
    Supported %in% c("Supported", "supported") ~ "Supported",
    Supported %in% c("Not supported", "Not Supported", "not supported") ~ "Not supported",
    Supported %in% c("Neutral feelings", "Neutral feellings", "neutral feelings") ~ "Neutral feelings",
    TRUE ~ Supported
  ))


head(df_supported)
```

```{r}
contingency_table <- table(df_supported$Supported, df_supported$Changed)
chisq_test <- chisq.test(contingency_table)
p_value <- chisq_test$p.value
```

```{r}
summarized_df <- df_supported %>%
  group_by(Supported, Changed) %>%
  summarise(Count = n()) %>%
  ungroup()

summarized_df <- summarized_df %>%
  arrange(desc(Count)) %>%
  mutate(Supported = factor(Supported, levels = unique(Supported)))

ggplot(summarized_df, aes(x = Supported, y = Count, fill = Changed)) +
  geom_bar(stat = "identity", position = "dodge") +
  labs(title = "Impact of Institutional Support on Career Plans",
       x = "Institutional Support",
       y = "Count",
       fill = "Career Plan Change",
       caption = "Fig 3. The relationship between perceived institutional support and changes in academic or professional plans due to COVID-19,\nshowing increased change for those who felt unsupported.") +
  scale_fill_manual(values = c("NO CHANGE" = "grey70", "CHANGED" = "grey30")) +
  theme_minimal() +
  theme(plot.caption = element_text(hjust = 0, margin = margin(t = 0, r = 0, b = 0, l = 0), size = 16))
```

```{r}
df_filtered <- df_supported %>%
  filter(Supported %in% c("Not supported", "Supported", "Neutral feelings"))

summarized_df <- df_filtered %>%
  group_by(Supported, Changed) %>%
  summarise(Count = n()) %>%
  mutate(Proportion = Count / sum(Count)) %>%
  ungroup()

summarized_df$Supported <- factor(summarized_df$Supported, levels = c("Supported", "Not supported", "Neutral feelings"))

ggplot(summarized_df, aes(x = Supported, y = Proportion, fill = Changed)) +
  geom_bar(stat = "identity", position = "dodge") +
  labs(title = "Impact of Institutional Support on Career Plans",
       x = "Institutional Support",
       y = "Proportion",
       fill = "Career Plan Change",
       caption = "Fig 1. The relationship between perceived institutional support and changes in academic or professional plans due to COVID-19,\nshowing signifcant association between support and career plan change, as shown from p-value from chi-square test of independence.") +
  scale_fill_manual(values = c("NO CHANGE" = "grey70", "CHANGED" = "grey30")) +
  theme_minimal() +
  scale_y_continuous(labels = scales::percent_format(), limits = c(0, 1)) +
  theme(plot.caption = element_text(hjust = 0, margin = margin(t = 0, r = 0, b = 0, l = 0), size = 16)) +
  geom_segment(aes(x = 1 - 0.25, xend = 2 - 0.25, y = 0.75, yend = 0.75)) +
  geom_segment(aes(x = 1 - 0.25, xend = 1 - 0.25, y = 0.35, yend = 0.75)) +
  geom_segment(aes(x = 2 - 0.25, xend = 2 - 0.25, y = 0.73, yend = 0.75)) +
  geom_segment(aes(x = (1.75 + 0.75) / 2, xend = (1.75 + 0.75) / 2, y = 0.75, yend = 0.765)) +
  annotate("text", x = (1.75 + 0.75) / 2, y = 0.78, label = paste("p-value:", format(p_value, scientific = TRUE)))

```

## Race & Gender & Role Support

```{r}
df_supported <- data %>% 
  rename(Supported = Did.you.feel.supported.from.your.institution..department..team..etc...,
         Race = What.is.your.race.and.or.ethnicity..Check.all.that.apply....Selected.Choice,
         Gender = How.would.you.describe.yourself...Mark.one.answer....Selected.Choice
         ) %>% 
  select(Race, Gender, Role, Supported)

df_supported <- df_supported %>%
  mutate(Supported = case_when(
    Supported %in% c("Supported", "supported") ~ "Supported",
    Supported %in% c("Not supported", "Not Supported", "not supported") ~ "Not supported",
    Supported %in% c("Neutral feelings", "Neutral feellings", "neutral feelings") ~ "Neutral feelings",
    Supported == "" ~ "Not coded yet",
    TRUE ~ Supported
  ))

df_supported <- df_supported %>%
  filter(Supported %in% c("Supported", "Not supported"))
df_supported <- df_supported %>%
  separate_rows(Race, sep = ",\\s*")
```

```{r}
df_race <- df_supported %>%
  group_by(Race, Supported) %>%
  summarise(count = n()) %>%
  mutate(proportion = count / sum(count))

ggplot(df_race, aes(x = Race, y = proportion, fill = Supported)) +
  geom_bar(stat = "identity", position = "dodge") +
  scale_y_continuous(labels = scales::percent_format()) +
  scale_fill_grey(start = 0.8, end = 0.2) +
  labs(title = "Support Levels by Race",
       x = "Race",
       y = "Proportion",
       fill = "Support Level") +
  theme_minimal() +
  coord_flip()

df_gender <- df_supported %>%
  group_by(Gender, Supported) %>%
  summarise(count = n()) %>%
  mutate(proportion = count / sum(count))

ggplot(df_gender, aes(x = Gender, y = proportion, fill = Supported)) +
  geom_bar(stat = "identity", position = "dodge") +
  scale_y_continuous(labels = scales::percent_format()) +
  scale_fill_grey(start = 0.8, end = 0.2) +
  labs(title = "Support Levels by Gender",
       x = "Gender",
       y = "Proportion",
       fill = "Support Level") +
  theme_minimal() +
  coord_flip()

df_role <- df_supported %>%
  group_by(Role, Supported) %>%
  summarise(count = n()) %>%
  mutate(proportion = count / sum(count))

ggplot(df_role, aes(x = Role, y = proportion, fill = Supported)) +
  geom_bar(stat = "identity", position = "dodge") +
  scale_y_continuous(labels = scales::percent_format()) +
  scale_fill_grey(start = 0.8, end = 0.2) +
  labs(title = "Support Levels by Role",
       x = "Role",
       y = "Proportion",
       fill = "Support Level") +
  theme_minimal() +
  coord_flip()
```

## Race & Gender & Role Career Change

```{r}
df_supported <- data %>% 
  rename(Changed = How.has.COVID.19.changed.and.or.altered.your.academic.or.professional.plans...Some.examples..programs.you.will.apply.to..jobs.you.will.apply.to..interest.level.in.certain.career.paths.,
         Race = What.is.your.race.and.or.ethnicity..Check.all.that.apply....Selected.Choice,
         Gender = How.would.you.describe.yourself...Mark.one.answer....Selected.Choice
         ) %>% 
  select(Race, Gender, Role, Changed)

df_supported <- df_supported %>%
  separate_rows(Race, sep = ",\\s*") %>% 
  mutate(Gender := str_trim(Gender)) %>% 
  mutate(Gender := case_when(
      Gender %in% c("Nonbinary", "Agender", "Genderfluid, Genderqueer, or Gender Non-conforming") ~ "Genderqueer",
      TRUE ~ as.character(Gender)
    ))
```

```{r}
df_race <- df_supported %>%
  group_by(Race, Changed) %>%
  summarise(count = n()) %>%
  mutate(proportion = count / sum(count))

ggplot(df_race, aes(x = Race, y = proportion, fill = Changed)) +
  geom_bar(stat = "identity", position = "dodge") +
  scale_y_continuous(labels = scales::percent_format()) +
  scale_fill_grey(start = 0.8, end = 0.2) +
  labs(title = "Career Plan Change by Race",
       x = "Race",
       y = "Proportion",
       fill = "Career Plan Change") +
  theme_minimal() +
  coord_flip()

df_gender <- df_supported %>%
  group_by(Gender, Changed) %>%
  summarise(count = n()) %>%
  mutate(proportion = count / sum(count))

ggplot(df_gender, aes(x = Gender, y = proportion, fill = Changed)) +
  geom_bar(stat = "identity", position = "dodge") +
  scale_y_continuous(labels = scales::percent_format()) +
  scale_fill_grey(start = 0.8, end = 0.2) +
  labs(title = "Career Plan Change by Gender",
       x = "Gender",
       y = "Proportion",
       fill = "Career Plan Change") +
  theme_minimal() +
  coord_flip()

df_role <- df_supported %>%
  group_by(Role, Changed) %>%
  summarise(count = n()) %>%
  mutate(proportion = count / sum(count))

ggplot(df_role, aes(x = Role, y = proportion, fill = Changed)) +
  geom_bar(stat = "identity", position = "dodge") +
  scale_y_continuous(labels = scales::percent_format()) +
  scale_fill_grey(start = 0.8, end = 0.2) +
  labs(title = "Career Plan Change by Role",
       x = "Role",
       y = "Proportion",
       fill = "Career Plan Change") +
  theme_minimal() +
  coord_flip()
```

```{r}
df_supported <- df_supported %>% 
  filter(!Race %in% c("Decline to state", "Other (write-in)")) %>% 
  filter(!Gender %in% c("Decline to state", "Other (write-in)"))

df_updated_race <- df_supported %>%
  mutate(Race_Comparison = case_when(
    Race %in% c("White") ~ "White",
    TRUE ~ "BIPOC"
  )) %>%
  filter(Race_Comparison %in% c("White", "BIPOC"))
```

```{r}
race_counts <- df_updated_race %>%
  group_by(Race_Comparison, Changed) %>%
  summarise(count = n(), .groups = 'drop') %>%
  pivot_wider(names_from = Changed, values_from = count, values_fill = 0)

race_test <- chisq.test(as.matrix(race_counts[, -1]))
```

```{r}
df_woman_man <- df_supported %>%
  filter(Gender %in% c("Woman", "Man"))
contingency_table_woman_man <- table(df_woman_man$Gender, df_woman_man$Changed)
chisq_test_woman_man <- chisq.test(contingency_table_woman_man)
p_value_woman_man <- chisq_test_woman_man$p.value
df_genderqueer_man <- df_supported %>%
  filter(Gender %in% c("Genderqueer", "Man"))
contingency_table_genderqueer_man <- table(df_genderqueer_man$Gender, df_genderqueer_man$Changed)
chisq_test_genderqueer_man <- chisq.test(contingency_table_genderqueer_man)
p_value_genderqueer_man <- chisq_test_genderqueer_man$p.value

print(paste("p-value for Woman vs Man: ", format(p_value_woman_man, scientific = TRUE)))
print(paste("p-value for Genderqueer vs Man: ", format(p_value_genderqueer_man, scientific = TRUE)))
```

```{r}
df_race <- df_supported %>%
  group_by(Race, Changed) %>%
  summarise(count = n()) %>%
  mutate(proportion = count / sum(count)) %>% 
  filter(Changed == "CHANGED")%>%
  arrange(-desc(proportion))

df_race$Race <- factor(df_race$Race, levels = df_race$Race)

race_graph <- ggplot(df_race, aes(x = proportion, y = Race)) +
  geom_bar(stat = "identity") +
  scale_x_continuous(labels = scales::percent_format(), limits = c(0, 1)) +
  scale_fill_grey(start = 0.8, end = 0.2) +
  labs(title = "Race",
       x = "",
       y = "") +
  theme_minimal() +
  geom_segment(aes(x = 0.725, xend = 0.725, y = "Asian", yend = "American Indian or Alaska Native")) + 
  geom_segment(aes(x = 0.7, xend = 0.725, y = "Asian")) + 
  geom_segment(aes(x = 0.55, xend = 0.725, y = "American Indian or Alaska Native")) + geom_segment(aes(x = 0.725, xend = 0.73, y = "Hispanic or Latinx")) +
  annotate("text", x = 0.73, y = "Hispanic or Latinx", label = "BIPOC", hjust = 0) + geom_signif(comparisons = list(c("Hispanic or Latinx", "White")),
              annotations = paste("p-value:", format(race_test$p.value, scientific = TRUE)), y = 0.775)
  


df_gender <- df_supported %>%
  group_by(Gender, Changed) %>%
  summarise(count = n()) %>%
  mutate(proportion = count / sum(count)) %>% 
  filter(Changed == "CHANGED")%>%
  arrange(-desc(proportion))

df_gender$Gender <- factor(df_gender$Gender, levels = df_gender$Gender)

gender_graph <- ggplot(df_gender, aes(x = proportion, y = Gender)) +
  geom_bar(stat = "identity") +
  scale_x_continuous(labels = scales::percent_format(), limits = c(0, 1)) +
  scale_fill_grey(start = 0.8, end = 0.2) +
labs(title = "Gender",
     x = "",
     y = "") +
theme_minimal() +
  geom_signif(comparisons = list(c("Genderqueer", "Man")),
              annotations = paste("p-value:", format(p_value_genderqueer_man, scientific = TRUE))) +
  geom_signif(comparisons = list(c("Woman", "Man")),
              annotations = paste("p-value:", format(p_value_woman_man, scientific = TRUE)), y = 0.6)

race_graph / gender_graph +
plot_layout(guides = "collect") &
plot_annotation(
  title = "Career Plan Change Due to COVID-19 by Race & Gender",
  caption = "Fig 2. Career plan changes due to COVID-19 by racial and gender groups. Shows underrepresented groups exhibited higher levels of change\nas seen from p-value from chi-square tests of independence.",
  theme = theme(plot.caption = element_text(hjust = 0, margin = margin(t = 0, r = 0, b = 0, l = 0), size = 16))
)
```

## Changed By Supported by Race

```{r}
df_supported <- data %>% 
  rename(Supported = Did.you.feel.supported.from.your.institution..department..team..etc...,
         Changed = How.has.COVID.19.changed.and.or.altered.your.academic.or.professional.plans...Some.examples..programs.you.will.apply.to..jobs.you.will.apply.to..interest.level.in.certain.career.paths.,
         Race = What.is.your.race.and.or.ethnicity..Check.all.that.apply....Selected.Choice,
         Gender = How.would.you.describe.yourself...Mark.one.answer....Selected.Choice
         ) %>% 
  select(Race, Gender, Changed, Supported)

df_supported <- df_supported %>%
  mutate(Supported = case_when(
    Supported %in% c("Supported", "supported") ~ "Supported",
    Supported %in% c("Not supported", "Not Supported", "not supported") ~ "Not supported",
    Supported %in% c("Neutral feelings", "Neutral feellings", "neutral feelings") ~ "Neutral feelings",
    Supported == "" ~ "Not coded yet",
    TRUE ~ Supported
  ))

df_supported <- df_supported %>%
  filter(Supported %in% c("Supported", "Not supported"))
df_supported <- df_supported %>%
  separate_rows(Race, sep = ",\\s*") %>% 
  mutate(Gender := str_trim(Gender)) %>% 
  mutate(Gender := case_when(
      Gender %in% c("Nonbinary", "Agender", "Genderfluid, Genderqueer, or Gender Non-conforming") ~ "Genderqueer",
      TRUE ~ as.character(Gender)
    ))

df_supported <- df_supported %>% 
  filter(!Race %in% c("Decline to state", "Other (write-in)")) %>% 
  filter(!Gender %in% c("Decline to state", "Other (write-in)"))
```

```{r}
df_race <- df_supported %>%
  group_by(Race, Changed, Supported) %>%
  summarise(count = n()) %>%
  mutate(proportion = count / sum(count))

df_gender <- df_supported %>%
  group_by(Gender, Changed, Supported) %>%
  summarise(count = n()) %>%
  mutate(proportion = count / sum(count))
```

```{r}
df_race <- df_race %>%
  mutate(Support_Change = interaction(Supported, Changed))

ggplot(df_race, aes(x = proportion, y = reorder(Race, proportion), fill = Support_Change)) +
  geom_bar(stat = "identity") +
  geom_text(aes(label = proportion), position = position_dodge(width = 0.8), hjust = -0.1)+
  facet_wrap(~ Support_Change) +
  scale_x_continuous(labels = scales::percent_format()) +
  scale_fill_grey(start = 0.8, end = 0.2, name = "Support Status and Change") +
  labs(title = "Impact of Institutional Support on Career Plan Changes by Race",
       x = "Proportion of Responses",
       y = "Race") +
  theme_minimal() +
  theme(axis.text.x = element_text(angle = 45, hjust = 1))
```

```{r}
df_updated_race <- df_supported %>%
  mutate(Race_Comparison = case_when(
    Race %in% c("White") ~ "White",
    TRUE ~ "BIPOC"
  )) %>%
  filter(Race_Comparison %in% c("White", "BIPOC"))
 
df_race <- df_updated_race %>%
  group_by(Race_Comparison, Changed, Supported) %>%
  summarise(count = n()) %>%
  mutate(proportion = count / sum(count)) %>% 
  ungroup() %>% 
  pivot_wider(names_from = Race_Comparison, values_from = c(count,proportion)) %>%
  mutate(difference = proportion_BIPOC  - proportion_White)
df_race
```

```{r}
df_gender <- df_gender %>%
  mutate(Support_Change = interaction(Supported, Changed))

ggplot(df_gender, aes(x = proportion, y = reorder(Gender, proportion), fill = Support_Change)) +
  geom_bar(stat = "identity") +
  geom_text(aes(label = proportion), position = position_dodge(width = 0.8), hjust = -0.1)+
  facet_wrap(~ Support_Change) +
  scale_x_continuous(labels = scales::percent_format()) +
  scale_fill_grey(start = 0.8, end = 0.2, name = "Support Status and Change") +
  labs(title = "Impact of Institutional Support on Career Plan Changes by Gender",
       x = "Proportion of Responses",
       y = "Gender") +
  theme_minimal() +
  theme(axis.text.x = element_text(angle = 45, hjust = 1))
```

```{r}
summarized_df <- df_supported %>%
  group_by(Race, Supported) %>%
  summarise(Count = n()) %>%
  mutate(proportion = Count / sum(Count))

ggplot(summarized_df, aes(x = proportion, y = Race, fill = Supported)) +
  geom_bar(stat = "identity", position = "dodge") +
  labs(title = "Feelings of Support by Race",
       x = "Proportion",
       y = "")
```

```{r}
ggplot(df_race, aes(x = Race, y = proportion , fill = Supported)) +
  geom_bar(stat = "identity") +
  facet_wrap(~ Changed) +
  scale_y_continuous(labels = scales::percent_format()) +
  scale_fill_grey(start = 0.8, end = 0.2, name = "Support Status") +
  labs(title = "Impact of Institutional Support on Career Plan Changes by Race",
       x = "Race",
       y = "Proportion of Responses") +
  theme_minimal() +
  theme(axis.text.x = element_text(angle = 45, hjust = 1))
```

```{r}
df_race <- df_supported %>%
  group_by(Race, Changed, Supported) %>%
  summarise(count = n(), .groups = 'drop') %>%
  group_by(Race, Supported) %>%
  mutate(total_count = sum(count),
         proportion = count / total_count) %>%
  ungroup()
ggplot(df_race, aes(x = Race, y = proportion , fill = Supported)) +
  geom_bar(stat = "identity") +
  facet_wrap(~ Changed) +
  scale_y_continuous(labels = scales::percent_format()) +
  scale_fill_grey(start = 0.8, end = 0.2, name = "Support Status") +
  labs(title = "Impact of Institutional Support on Career Plan Changes by Race",
       x = "Race",
       y = "Proportion of Responses") +
  theme_minimal() +
  theme(axis.text.x = element_text(angle = 45, hjust = 1))
```

```{r}
df_race <- df_race %>%
  mutate(Support_Change = interaction(Supported, Changed))

ggplot(df_race, aes(x = proportion, y = reorder(Race, proportion), fill = Support_Change)) +
  geom_bar(stat = "identity") +
  geom_text(aes(label = proportion), position = position_dodge(width = 0.8), hjust = -0.1)+
  facet_wrap(~ Support_Change) +
  scale_x_continuous(labels = scales::percent_format()) +
  scale_fill_grey(start = 0.8, end = 0.2, name = "Support Status and Change") +
  labs(title = "Impact of Institutional Support on Career Plan Changes by Race",
       x = "Proportion of Responses",
       y = "Race") +
  theme_minimal() +
  theme(axis.text.x = element_text(angle = 45, hjust = 1))
```

```{r}
df_race <- df_supported %>%
  group_by(Race, Changed, Supported) %>%
  summarise(count = n()) %>%
  mutate(proportion = count / sum(count),
         total_support = sum(count))

overall_support <- df_supported %>%
  group_by(Race, Supported) %>%
  summarise(count = n()) %>%
  mutate(overall_proportion = count / sum(count),
         total_race = sum(count))

df_race_deviation <- df_race %>%
    left_join(overall_support, by = c("Race", "Supported")) %>%
    mutate(deviation_from_mean = proportion - overall_proportion) %>% 
    filter(Supported == "Supported",
           Changed == "NO CHANGE")
```

```{r}
label_data_1 <- df_race_deviation %>% 
  filter(Race == "American Indian or Alaska Native")
label_data_2 <- df_race_deviation %>%
  filter(Race == "White")

race_graph <- df_race_deviation %>% ggplot(aes(x = deviation_from_mean, y = reorder(Race, deviation_from_mean))) +
  geom_bar(stat = "identity", position = "dodge") +
  scale_x_continuous(labels = scales::percent_format()) +
  labs(title = "Race",
       x = "",
       y = "") +
  theme_minimal() +
  xlim(0,0.4) +
    geom_label_repel(data = label_data_1, 
                   aes(label = "Largest increase in percieved institutional support"),
                   nudge_x = 0.1, 
                   color = "black", 
                   box.padding = 0.5, 
                   point.padding = 0.5, 
                   segment.color = 'grey50',
                   show.legend = FALSE)+
    geom_label_repel(data = label_data_2, 
                   aes(label = "Smallest increase in percieved institutional support"),
                   nudge_x = 0.1, 
                   color = "black", 
                   box.padding = 0.5, 
                   point.padding = 0.5, 
                   segment.color = 'grey50',
                   show.legend = FALSE)+
  theme(axis.title.x = element_blank(),
        axis.text.x = element_blank(),
        axis.ticks.x = element_blank())
```

```{r}
df_gender <- df_supported %>%
  group_by(Gender, Changed, Supported) %>%
  summarise(count = n()) %>%
  mutate(proportion = count / sum(count),
         total_support = sum(count))

overall_support <- df_supported %>%
  group_by(Gender, Supported) %>%
  summarise(count = n()) %>%
  mutate(overall_proportion = count / sum(count))

df_gender_deviation <- df_gender %>%
    left_join(overall_support, by = c("Gender", "Supported")) %>%
    mutate(deviation_from_mean = proportion - overall_proportion) %>% 
    filter(Supported == "Supported", Changed == "NO CHANGE")
```

```{r}
label_data_1 <- df_gender_deviation %>%
  filter(Gender == "Genderqueer")
label_data_2 <- df_gender_deviation %>%
  filter(Gender == "Man")

gender_graph <- df_gender_deviation %>% 
  ggplot(aes(x = deviation_from_mean, y = reorder(Gender, deviation_from_mean))) +
  geom_bar(stat = "identity", position = "dodge") +
  scale_x_continuous(labels = scales::percent_format()) +
  labs(title = "Gender",
       x = "",
       y = "") +
  theme_minimal() +
  xlim(0,0.4)+
    geom_label_repel(data = label_data_1, 
                   aes(label = "Largest increase in percieved institutional support"),
                   nudge_x = 0.1, 
                   color = "black", 
                   box.padding = 0.5, 
                   point.padding = 0.5, 
                   segment.color = 'grey50',
                   show.legend = FALSE)+
    geom_label_repel(data = label_data_2, 
                   aes(label = "Smallest increase in percieved institutional support"),
                   nudge_x = 0.1, 
                   color = "black", 
                   box.padding = 0.5, 
                   point.padding = 0.5, 
                   segment.color = 'grey50',
                   show.legend = FALSE)
```

```{r}
race_graph / gender_graph +   
  plot_annotation(
    caption = "Figure 4. Deviation from the respective group mean proportion of perceived institutional support by race and gender for individuals who did not change their career intentions, ordered\ndecreasingly. Thus top groups saw the largest increase in percieved institutional support (of those who did not express change in career intentions). Data suggest underrepresented\nindividuals who did not express change in career intentions percieved more feelings of institutional support.",
    theme = theme(plot.caption = element_text(hjust = 0, margin = margin(t = 0, r = 0, b = 0, l = 0), size = 16))
  )

```

```{r}
df <- df_supported %>%
  mutate(
    Supported = factor(Supported, levels = c("Not supported", "Supported")),
    Changed = factor(Changed, levels = c("CHANGED", "NO CHANGE")),
    Gender = factor(Gender, levels = c("Genderqueer", "Woman", "Man")),
    Race = factor(ifelse(Race == "White", "White", "BIPOC"), levels = c("White", "BIPOC"))
  )

model_interaction <- glm(Supported ~ Race:Changed, data = df, family = binomial)

summary(model_interaction)
```

```{r}
model_interaction <- glm(Supported ~ Gender:Changed, data = df, family = binomial)

summary(model_interaction)
```
